drop table if exists vehicle CASCADE;
create table vehicle (id integer generated by default as identity, doors integer not null, name varchar(255) not null, wheels integer not null, primary key (id));